kind: "ReplicationController"
apiVersion: "v1"
metadata: 
  name: "redis-master"
  labels: 
    app: "redis"
    role: "master"
spec: 
  replicas: 1
  selector: 
    app: "redis"
    role: "master"
  template: 
    metadata: 
      labels: 
        app: "redis"
        role: "master"
    spec: 
      containers: 
        - name: "redis-master"
          image: "wallnerryan/redis"
          env:
          - name: GET_HOSTS_FROM
            value: env
          command: ["/usr/bin/redis-server", "--appendonly","yes"]
          ports: 
            - name: "redis-server"
              containerPort: 6379
          volumeMounts:
            - name: redis-master-data
              mountPath: "/var/lib/redis"
      volumes:
        - name: redis-master-data
          flocker:
            datasetName: flocker-redis-master